### ISSUE TITLE
PR tests returning status code 500 don't have any further information

### ISSUE THREAD

**Issue by FichteFoll** [wbond/packagecontrol.io#102]
Whenever a PR test fails to run, I only receive `{"__status_code__": 500}` as the answer, with no context information whatsoever. Going through [run_repo_tests.py](https://github.com/wbond/packagecontrol.io/blob/master/app/lib/run_repo_tests.py), it doesn't look like `__status_code__` is ever set without at least also setting `error` and `message`, so I suspect that the result data gets overwritten when the status is set [here](https://github.com/wbond/packagecontrol.io/blob/7b5c521d528bd36c04543014fd49326ee83da5c0/app/controllers/test_pr.py#L16), or later in the pipeline.

Example: https://github.com/wbond/package_control_channel/pull/6937, https://travis-ci.org/wbond/package_control_channel/builds/339309986#L452

**Comment by wbond** [comment]
A 500 should never be expected - it just means there was a programming error in the website code.
