### ISSUE TITLE
Manual review for SublimeLinter-eslint

### ISSUE THREAD

**Issue by akrikos** [wbond/packagecontrol.io#132]
Hi there, I'm NOT the owner of SublimeLinter-eslint, but would like to be able to install it. Looks like it has been flagged by the new "needs review" process described in the latest news post. Is there anything I can do to help?

An issue was created on the SublimeLinter-eslint repo as well (https://github.com/SublimeLinter/SublimeLinter-eslint/issues/306)

**Comment by braver** [comment]
@wbond a number of SublimeLinter packages are marked as requiring review. What does that proces entail and is there a way for me to expedite it?

**Comment by wbond** [comment]
Sorry guys, due to stuff in my personal life I haven’t been at a machine really since last Tuesday. I’ll try to get to this as soon as I can.

**Comment by akrikos** [comment]
Life is more important than this stuff. I hope things go as well as they can for you.

**Comment by wbond** [comment]
This was taken care of a while ago
