### ISSUE TITLE
Manual review for Wallaby and Quokka packages

### ISSUE THREAD

**Issue by ArtemGovorov** [wbond/packagecontrol.io#136]
Hello @wbond,

two of our packages had recently stopped showing in the Package Control: Install Package command search.

https://packagecontrol.io/packages/Wallaby
https://packagecontrol.io/packages/Quokka

On the packages pages there’s the `NEEDS REVIEW` label with the `Package was previously missing and needs manual review to re-enable` title.

Can you please review and restore the packages in package control?

**Comment by wbond** [comment]
This was taken care of a while ago
