### ISSUE TITLE
Email links in README files are broken.

### ISSUE THREAD

**Issue by davidolrik** [wbond/packagecontrol.io#38]
Bare email addresses are turned into links prefixed with the GutHub url prefix.
I tried to remedy the problem by creating a specific mailto: link but it is still prefixed incorrectly.

    https://raw.githubusercontent.com/davidolrik/sublime-rsync-ssh/master/mailto:david@olrik.dk

Example is taken from here https://packagecontrol.io/packages/Rsync%20SSH

**Comment by wbond** [comment]
This was fixed by 72f39e3420d3cecedf79fccb4cc407487ecc387e
