### ISSUE TITLE
Lag in the search box

### ISSUE THREAD

**Issue by FichteFoll** [wbond/packagecontrol.io#42]
So, this is the same issue as reported at https://github.com/wbond/package_control/issues/875, but it was really annoying for me for probably a year, which is why I finally decided to create an issue. I remember mentioning this at some point but probably only in a "by the way" clause.

Basically, what seems to be happening is that after a certain delay a "search" gets triggered for live preview and the search box is set with the text the search was issued with as the reply is received, which results in the following:

1. Any text input entered between the submission of the "current" text value and the receival of the server's reply is just lost since it's replaced with the initial text of the search query.
2. The caret is always put to the end of the input (and selection is cleared).

Certain timing is necessary to trigger 1. so that the text is entered during that short time frame.

Example show casing both cases:
As explained in the referenced issue, type "abc", then select all text using ctrl+a and type 123.
If I am fast enough I get `asd23` or `asd3` in the input field.

**Comment by wbond** [comment]
Thanks for posting this here. I occasionally have run into, but haven't gotten around to fixing it yet.

I will hopefully get this resolved soon.

**Comment by wbond** [comment]
I believe this should be fixed by 4858d7abf5ea0e2b8a72af587296a482559eae5e

**Comment by FichteFoll** [comment]
Unfortunately, 

>The caret is always put to the end of the input (and selection is cleared).

still happens.
