### ISSUE TITLE
pybars requirement

### ISSUE THREAD

**Issue by gbaptista** [wbond/packagecontrol.io#52]
`Could not find a version that satisfies the requirement pybars==0.0.5 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4)
No matching distribution found for pybars==0.0.5`

Only version 0.0.4 is available... (https://pypi.python.org/pypi/pybars)

(https://github.com/wbond/packagecontrol.io/blob/master/setup/requirements.txt#L13)

**Comment by wbond** [comment]
There were instructions in `development.md` that had you install a custom python3 compatible version of pybars, but with f4be7d5934888e8ef4b5c57ad07fdf7c006f6938 I've just updated it to use my newer pybars3 library.
