### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by DarwinniwraD** [wbond/packagecontrol.io#66]
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.

**Comment by wbond** [comment]
Linode (where the server is hosted), is under a massive DDoS attack. http://status.github.com

**Comment by wbond** [comment]
Please see https://github.com/wbond/package_control/issues/1057 for more information
