### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by idleberg** [wbond/packagecontrol.io#85]
I have noticed another problem since the downtime of the crawler: packages that have been renamed are reportes missing. Maybe will fix itself, but I wanted to report it nevertheless.
![image](https://cloud.githubusercontent.com/assets/1504938/18395954/588e506c-76c1-11e6-8046-c534dc7c7494.jpeg)

**Comment by idleberg** [comment]
Problem solved

**Comment by wbond** [comment]
Yes, I just confirmed – thanks for reporting.
