### ISSUE TITLE
generate readme from current release

### ISSUE THREAD

**Issue by niosus** [wbond/packagecontrol.io#88]
After a new release is published the readme generated on Package Control website stays old for undefined periods of time. It is very confusing and misleading for the users! I think this is really a big issue. 

Or at least, let us specify a special readme exclusively for Package Control basically to just point to the actual readme on the GitHub page. 

This may also be related to #77

**Comment by FichteFoll** [comment]
https://github.com/wbond/package_control/blob/2bcface6c34544eb5b0258984f2803b7a3c98ffc/example-repository.json#L113-L134

By default, the website renders the readme file of the repository's master branch.

**Comment by niosus** [comment]
Oh, nice didn't know about it. Thanks.
