### ISSUE TITLE
Change keyboard shortcut for "Search" bar focus

### ISSUE THREAD

**Issue by ZaLiTHkA** [wbond/packagecontrol.io#89]
As far as I know, most browsers reserve the shortcut `ctrl+shift+p` for a print dialog (I know at least Chrome does), so in the end this shortcut isn't all that useful...

Over the years I've seen a few other sites that simply used `/` as the search bar shortcut, so could we perhaps have that instead?

I found [a line here](https://github.com/wbond/packagecontrol.io/blob/master/public/js/app.js#L18883) that appears to be setting the shortcut, but I'm not familiar at all with "keymaster.js", nor the structure of your website build system, so I thought it would be safer to post a request rather than a pull request.

What do you think @wbond?

**Comment by FichteFoll** [comment]
https://github.com/wbond/packagecontrol.io/issues/28

**Comment by ZaLiTHkA** [comment]
Apologies for yet another duplicate issue.. I've left a comment on 28 instead. :)
