### ISSUE TITLE
how many user are using St2/3

### ISSUE THREAD

**Issue by math2001** [wbond/packagecontrol.io#90]
Hello!

Thank you so much for package control, I don't know how I would manage my st packages without it. 👍

In the [stats](https://packagecontrol.io/stats) page, I've seen that you're able to say if a user is using window, linux, or osx, so I guess you could tell us if they're using st2 or st3. It would be quite helpful to see if it's worth supporting st2. Would it be hard to do?

I opened this issue on the `package_control` repo, but @FichteFoll told me that this one was the right place, and in the same time, this:

> Information on beta vs dev channel would also be useful (exact build numbers even more so, but most likely not necessary).

Thank you again,

Matt

**Comment by wbond** [comment]
In the past three months:

 - ~24 million package operations occurred
 - 91% of package operations were done via Sublime Text 3
 - 9% of package operations were done via Sublime Text 2

Weird stats:
 - 6.5% of package operations were done by versions of ST3 before build 3103
 - 2,500 package operations were done with build 3021 (a dev build from 2013)
 - over 15,000 package operations were done of builds of ST2 older than the most recent stable build

At some point I'll probably add this to the site. Hope this is helpful for now.

**Comment by FichteFoll** [comment]
Yes, thank you. Do you have a few numbers for 3125 vs 3126 though, being the latest releases of each channel respectively?

**Comment by wbond** [comment]
The past three months covers multiple beta releases of ST3, so the following analysis is of the past month:

 - 74% - build 3126
 - 1.5% - build 3125
 - 9.0% - build 3114
 - 3.3% - build 3103
 - 3.2% - build 3083
 - 1.2% - build 3065
 - 5.5% - build 2221

No other build has more than 1% usage. ST3 accounts for 94.5% of all usage.

**Comment by math2001** [comment]
> At some point I'll probably add this to the site.

Looking forward to that!

**Comment by gour** [comment]
Very interesting stats! Thank you for providing it. ;)
