### ISSUE TITLE
ST build 3143 support

### ISSUE THREAD

**Issue by pr301** [wbond/packagecontrol.io#96]
steps to reproduce
1) update ST to build 3143
2) hit shift+cmd+p
3) look for anything that has to do with package control

expected:
we should have options to install packages etc etc

actual:
looks like package control is not there at all

workarounds tried:
- use the python snippet from the installation instructions for package control to install it (didn't work)
- manually install package control in the Packages folder (ST-->settings-->browse packages) (didn't work)

**Comment by FichteFoll** [comment]
Check whether it is disabled in your user settings file.

**Comment by pr301** [comment]
nice one.. :) it was in the ignored_packages probably cause of the update..

thanks a lot 👍
