### ISSUE TITLE
Simple Installation Instructions

### ISSUE THREAD

**Issue by keith-hall** [wbond/packagecontrol.io#97]
Now that ST 3.0 is out, its probably safe to say that the simplest method of installing Package Control is no longer the console, but the Tools menu :)

https://github.com/wbond/packagecontrol.io/blob/9645b34334cb24584104e6d098b41329a177d628/app/html/installation.html#L8

**Comment by wbond** [comment]
This was addressed in 0c05b89b726e67b505ffb5433ddfca8d746ca992. It hasn't been deployed yet since I need to test some other changes before deploying.
